# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class Collection(Enum):
    """
    检索的实体集合。papers（默认，论文）/ authors（作者）/ sources（来源期刊）。 各 collection 字段集不同，用 list_catalog（collection=<name>）学习对应 schema。 注意：本工具的便捷字段（authors/journals/year_from/subjects 等）只对 papers 有意义； 查 authors/sources 时改用 filters_advanced + 该 collection 的字段名（如 authors 的 summary_stats.h_index / orcid，sources 的 issn / is_oa）。authors 用 orcid、 sources 用 issn 与论文检索结果关联。
    """

    papers = "papers"
    authors = "authors"
    sources = "sources"


class Operator(Enum):
    """
    过滤操作符。MATCH（分词模糊）适用于 author、keywords（输入 "Hinton" 命中 "Geoffrey Hinton"）； MATCH_PHRASE（短语模糊）适用于 publication_venue_name_unified，整词连续匹配（"Nature" 命中 "Nature Communications"；非前缀匹配，"Nature Comm" 不会命中）； doi 用 EQ，服务端归一化（去 doi.org 前缀+转小写）后精确匹配。MATCH/MATCH_PHRASE 仅对配了 text 子字段的字段有效。
    """

    FILTER_OP_EQ = "FILTER_OP_EQ"
    FILTER_OP_NE = "FILTER_OP_NE"
    FILTER_OP_GT = "FILTER_OP_GT"
    FILTER_OP_GTE = "FILTER_OP_GTE"
    FILTER_OP_LT = "FILTER_OP_LT"
    FILTER_OP_LTE = "FILTER_OP_LTE"
    FILTER_OP_IN = "FILTER_OP_IN"
    FILTER_OP_NIN = "FILTER_OP_NIN"
    FILTER_OP_CONTAINS = "FILTER_OP_CONTAINS"
    FILTER_OP_MATCH = "FILTER_OP_MATCH"
    FILTER_OP_MATCH_PHRASE = "FILTER_OP_MATCH_PHRASE"


class FiltersAdvancedItem(BaseModel):
    field: str
    operator: Operator | None = Field(
        "FILTER_OP_EQ",
        description='过滤操作符。MATCH（分词模糊）适用于 author、keywords（输入 "Hinton" 命中 "Geoffrey Hinton"）； MATCH_PHRASE（短语模糊）适用于 publication_venue_name_unified，整词连续匹配（"Nature" 命中 "Nature Communications"；非前缀匹配，"Nature Comm" 不会命中）； doi 用 EQ，服务端归一化（去 doi.org 前缀+转小写）后精确匹配。MATCH/MATCH_PHRASE 仅对配了 text 子字段的字段有效。',
    )
    value: Any


class Order(Enum):
    SORT_ORDER_DESC = "SORT_ORDER_DESC"
    SORT_ORDER_ASC = "SORT_ORDER_ASC"


class SortAdvancedItem(BaseModel):
    field: str
    order: Order


class SortByYear(Enum):
    desc = "desc"
    asc = "asc"
    none = "none"


class FreshnessBoost(Enum):
    """
    模糊搜索新鲜度加权：结果偏向新文献（仅 query 非空时生效；传排序
    （sort_by_year 非 none / sort_advanced）时被忽略，硬排优先）。
    MILD: 近 10 年加权，适合日常查文献；STRONG: 近 3 年加权，适合跟踪
    研究方向 / 追最新进展。与 impact_boost / language_affinity 可叠加
    （均为乘法因子）。boost 生效时为浅翻页：不产 next_cursor、不支持
    cursor 深翻页。

    """

    NONE = "NONE"
    MILD = "MILD"
    STRONG = "STRONG"


class ImpactBoost(Enum):
    """
    模糊搜索影响力加权：高被引文献在保留相关性的前提下上浮（仅 query
    非空时生效；传排序时被忽略）。MILD: 轻度上浮，相关性仍主导；
    STRONG: 明显偏向高被引。引用因子有界、零被引中性（不会归零）。
    与 freshness_boost / language_affinity 可叠加；boost 生效时为浅翻页。

    """

    NONE = "NONE"
    MILD = "MILD"
    STRONG = "STRONG"


class LanguageAffinity(Enum):
    """
    模糊搜索语言亲和加权：非 query 语言的结果降序、但不排除（仅 query
    非空时生效；传排序时被忽略）。目标语言由服务端从 query 文本判定
    （假名→ja / 谚文→ko / 汉字→zh / 拉丁→en，其他书写系统不生效）；
    语言未知的文献保持中性不降权。MILD: 非目标语言 ×0.5，跨语言强相关
    结果仍可上浮；STRONG: ×0.2，几乎只看目标语言。与 freshness_boost /
    impact_boost 可叠加；boost 生效时为浅翻页。要硬排除某语言请改用
    filters_advanced 的 language 字段（如 {"field":"language","value":"en"}，
    软硬两层语义不同：本参数只调序，filter 直接排除）。

    """

    NONE = "NONE"
    MILD = "MILD"
    STRONG = "STRONG"


class SearchPapersRequest(BaseModel):
    collection: Collection | None = Field(
        "papers",
        description="检索的实体集合。papers（默认，论文）/ authors（作者）/ sources（来源期刊）。 各 collection 字段集不同，用 list_catalog（collection=<name>）学习对应 schema。 注意：本工具的便捷字段（authors/journals/year_from/subjects 等）只对 papers 有意义； 查 authors/sources 时改用 filters_advanced + 该 collection 的字段名（如 authors 的 summary_stats.h_index / orcid，sources 的 issn / is_oa）。authors 用 orcid、 sources 用 issn 与论文检索结果关联。",
    )
    query: str | None = Field(
        None,
        description="BM25 全文关键词，匹配标题/摘要/期刊名/关键词字段。留空则纯靠结构化过滤。",
    )
    title_contains: str | None = Field(
        None, description="标题中必须包含的词（仅匹配 title 字段）。"
    )
    abstract_contains: str | None = Field(
        None, description="摘要中必须包含的词（仅匹配 abstract 字段）。"
    )
    authors: list[str] | None = Field(
        None,
        description="作者名（任一命中即可）。SDK 内部映射到后端 `author` 字段（FILTER_OP_IN）。",
    )
    year_from: int | None = Field(None, description="起始发表年（含）。")
    year_to: int | None = Field(None, description="结束发表年（含）。")
    journals: list[str] | None = Field(
        None,
        description="期刊名（任一命中即可）。SDK 内部映射到后端 `publication_venue_name_unified` 字段（FILTER_OP_IN，规范化后的载体名）。",
    )
    subjects: list[str] | None = Field(
        None, description='学科分类，如 "computer science"、"biology"。'
    )
    filters_advanced: list[FiltersAdvancedItem] | None = Field(
        None,
        description='高级过滤逃生舱（仅当上述字段不够用时使用）。可用字段见 get_field_catalog。\n\n引文反查（常用）：field="references_unique_id" 查「谁引用了某篇论文」，\nvalue 填目标论文的 unique_id。相比 list_paper_relations 的 CITATIONS，\n它支持深翻页与任意排序，适合超高被引论文。可叠加条件，\n例如「引用了 ResNet 且 2023 年后发表」：\n  [{"field":"references_unique_id","value":"paper:10.1109/cvpr.2016.90"},\n   {"field":"publication_published_year","operator":"FILTER_OP_GTE","value":2023}]\n该字段仅支持过滤，不能排序/聚合，也不能放进 fields 返回。\n',
    )
    sort_advanced: list[SortAdvancedItem] | None = Field(
        None,
        description="高级排序逃生舱（按任意可排序字段）。papers 用 sort_by_year 即可； authors/sources 想按 h-index / 被引 / works_count 排序时用本字段。 与 query 互斥（query 走相关性排序）。",
    )
    sort_by_year: SortByYear | None = "desc"
    freshness_boost: FreshnessBoost | None = Field(
        "NONE",
        description="模糊搜索新鲜度加权：结果偏向新文献（仅 query 非空时生效；传排序\n（sort_by_year 非 none / sort_advanced）时被忽略，硬排优先）。\nMILD: 近 10 年加权，适合日常查文献；STRONG: 近 3 年加权，适合跟踪\n研究方向 / 追最新进展。与 impact_boost / language_affinity 可叠加\n（均为乘法因子）。boost 生效时为浅翻页：不产 next_cursor、不支持\ncursor 深翻页。\n",
    )
    impact_boost: ImpactBoost | None = Field(
        "NONE",
        description="模糊搜索影响力加权：高被引文献在保留相关性的前提下上浮（仅 query\n非空时生效；传排序时被忽略）。MILD: 轻度上浮，相关性仍主导；\nSTRONG: 明显偏向高被引。引用因子有界、零被引中性（不会归零）。\n与 freshness_boost / language_affinity 可叠加；boost 生效时为浅翻页。\n",
    )
    language_affinity: LanguageAffinity | None = Field(
        "NONE",
        description='模糊搜索语言亲和加权：非 query 语言的结果降序、但不排除（仅 query\n非空时生效；传排序时被忽略）。目标语言由服务端从 query 文本判定\n（假名→ja / 谚文→ko / 汉字→zh / 拉丁→en，其他书写系统不生效）；\n语言未知的文献保持中性不降权。MILD: 非目标语言 ×0.5，跨语言强相关\n结果仍可上浮；STRONG: ×0.2，几乎只看目标语言。与 freshness_boost /\nimpact_boost 可叠加；boost 生效时为浅翻页。要硬排除某语言请改用\nfilters_advanced 的 language 字段（如 {"field":"language","value":"en"}，\n软硬两层语义不同：本参数只调序，filter 直接排除）。\n',
    )
    page: int | None = Field(1, ge=1)
    page_size: int | None = Field(10, ge=1, le=50)


class AuthorItem(BaseModel):
    name: str | None = None
    orcid: str | None = None


class PaperMetadata(BaseModel):
    """
    文献元数据。字段名与 metadata-service 后端 `fields.py` 的真实字段一致，
    SDK 不做响应转换。
    ---
    系统标识符两个分层（按需选用）:
      - `unique_id`: 元数据记录的全局唯一 ID。任何记录都有，与是否存在
        全文无关；适合做引用、去重、跨服务关联、引用图谱节点。
      - `doc_id`:    全文 artifact 的内容哈希（sha256）。仅在文档存在
        全文时返回；元数据-only 记录无此字段。要拉全文走 `read_content`
        接口必须用 doc_id。
    前端展示稳定 ID 用 unique_id；跨接口取全文用 doc_id。

    """

    unique_id: str = Field(
        ..., description="元数据记录的全局唯一 ID（任何记录都有，与是否有全文无关）。"
    )
    doc_id: str | None = Field(
        None,
        description="全文 artifact 的内容哈希（sha256）。仅当文档存在全文时返回；元数据-only 记录无此字段，且无法用 doc_id 过滤命中。",
    )
    is_content_accessible: bool | None = Field(
        None,
        description="正文对当前调用方是否可见 = 文档有全文（后端 access_xinghe_repository_process_status==1）且调用方被授权读全文 artifact。true 时可用 doc_id 调 read_content 取正文；false 表示无全文或无读取权限。服务端注入，不受 fields 投影影响。",
    )
    title: str
    author: list[AuthorItem] | None = Field(
        None,
        description='作者列表（OS object 数组，子字段 name/orcid）。按作者名检索：精确走 author.name.keyword、模糊 MATCH 走 author.name；对外过滤仍传 field "author"。',
    )
    abstract: str | None = None
    publication_venue_name_unified: str | None = Field(
        None,
        description="发表载体名称（期刊/会议；规范化形式——消除缩写/大小写/标点噪声，适合精确匹配/分组聚合）。",
    )
    publication_published_year: int | None = None
    subjects: list[str] | None = None
    keywords: list[str] | None = None
    doi: str | None = None


class SourceType(Enum):
    web = "web"
    pdf = "pdf"


class Filters(BaseModel):
    """
    结构化过滤（可选）。在召回阶段与语义检索同时生效（ES+Milvus 双引擎下推，
    不是结果后过滤）；多个字段之间 AND，同一字段传数组时数组内 OR。
    ⚠️ 宽松（软）语义：chunk 侧元数据缺失的文档不会被排除——例如按年份过滤时，
    缺年份信息的 chunk 仍可能返回。需要严格范围保证时勿当硬约束使用，
    表述结论时注明范围为"近似过滤"。
    数值/日期字段支持区间：{"gte":2020,"lte":2025} 或 [min,max]（null 表示一侧不限）；
    日期接受 YYYY / YYYY-MM / YYYY-MM-DD。
    实际可用字段受账号字段权限约束；未知字段服务端返回 400。
    例：{"author":["Hinton"],"publication_published_year":{"gte":2023},
        "topics":{"dimensions":{"primary_topic_domain":"Health Sciences"}}}

    """

    lang: Any | None = Field(
        None, description='语言代码，如 "en"、"zh"；也接受别名 language。'
    )
    metadata_type: Any | None = Field(
        None, description='资源类型，仅单值："paper" 或 "ebook"。'
    )
    author: Any | None = Field(
        None, description="作者名，string 或 string[]（数组=任一命中）。"
    )
    publication_venue_name_unified: Any | None = Field(
        None, description="发表载体名称（期刊/会议，规范化名，适合精确匹配）。"
    )
    publication_venue_type: Any | None = Field(
        None,
        description='载体类型："journal"、"conference"、"repository"、"book series"、"ebook platform"、"metadata"、"raidRegistry"、"igsnCatalog"、"other"（不区分大小写）。',
    )
    publication_published_year: Any | None = Field(
        None, description='发表年份，单值或区间（{"gte":..,"lte":..} / [min,max]）。'
    )
    publication_published_date: Any | None = Field(
        None, description='发表日期，"YYYY[-MM[-DD]]" 单值或区间。'
    )
    citation_count: Any | None = Field(None, description="被引次数，单值或区间。")
    influential_citation_count: Any | None = Field(
        None, description="高影响力被引次数，单值或区间。"
    )
    title: Any | None = Field(
        None, description="标题精确匹配（标题检索一般更适合 search_papers）。"
    )
    topics: Any | None = Field(
        None,
        description='主题组合过滤：{"logic":"and|or","dimensions":{"primary_topic":"...","primary_topic_domain":"Physical Sciences|Social Sciences|Health Sciences|Life Sciences"}}；logic 省略默认 or。',
    )
    doc_id: Any | None = Field(
        None,
        description="唯一的硬约束字段（其余字段均为软语义）：命中绝不越出给定集合。\n值为 64 位小写 hex sha256（即 search_papers 返回的 doc_id；仅有全文的论文才有），\nstring 或 string[]，仅 eq/in。去重后上限默认 1000，超限返回 400 SCOPE_TOO_LARGE；\n显式传空数组返回 200 空 hits（候选集为空，不退化为全局检索）。\n典型用法：先 search_papers 圈定候选集合，再在集合内做受限语义检索。\n",
    )


class Mode(Enum):
    """
    fast = 仅关键词召回 (~200ms)；balanced = 混合检索 (~600ms)；quality = LLM 改写 + 混合 (~2-4s)。

    """

    fast = "fast"
    balanced = "balanced"
    quality = "quality"


class SemanticSearchRequest(BaseModel):
    query: str = Field(
        ..., description="自然语言查询，1-200 字最佳。", max_length=4096, min_length=1
    )
    top_k: int | None = Field(
        10,
        description="返回命中条数上限，合法 1-100（服务端校验，超出报 400）。\n实际条数还受 mode 影响：balanced 单路混合召回在服务端固定截到约 50 条，\ntop_k 超过 50 时多出的部分不会返回；fast 与 quality 可取到 top_k。\n另外同一篇论文最多返回约 3 个 chunk，因此高 top_k 需要命中足够多的不同论文。\n",
        ge=1,
        le=100,
    )
    source_types: list[SourceType] | None = None
    filters: Filters | None = Field(
        None,
        description='结构化过滤（可选）。在召回阶段与语义检索同时生效（ES+Milvus 双引擎下推，\n不是结果后过滤）；多个字段之间 AND，同一字段传数组时数组内 OR。\n⚠️ 宽松（软）语义：chunk 侧元数据缺失的文档不会被排除——例如按年份过滤时，\n缺年份信息的 chunk 仍可能返回。需要严格范围保证时勿当硬约束使用，\n表述结论时注明范围为"近似过滤"。\n数值/日期字段支持区间：{"gte":2020,"lte":2025} 或 [min,max]（null 表示一侧不限）；\n日期接受 YYYY / YYYY-MM / YYYY-MM-DD。\n实际可用字段受账号字段权限约束；未知字段服务端返回 400。\n例：{"author":["Hinton"],"publication_published_year":{"gte":2023},\n    "topics":{"dimensions":{"primary_topic_domain":"Health Sciences"}}}\n',
    )
    mode: Mode | None = Field(
        "balanced",
        description="fast = 仅关键词召回 (~200ms)；balanced = 混合检索 (~600ms)；quality = LLM 改写 + 混合 (~2-4s)。\n",
    )


class SearchChunk(BaseModel):
    chunk_id: str
    doc_id: str
    title: str
    abstract: str | None = None
    chunk: str | None = None
    score: float
    offset: int = Field(
        ..., description="chunk 在原文中的字节偏移，可直接传给 read_content。"
    )
    page_no: int | None = None
    source_type: str | None = None


class ReadContentResponse(BaseModel):
    text: str
    bytes_returned: int
    next_offset: int
    more: bool = Field(
        ..., description="为 true 表示可能还有后续字节，可用 next_offset 继续请求。"
    )


class FieldCatalogEntry(BaseModel):
    name: str = Field(
        ..., description="字段名（与 search_papers 的 filters[].field 一致）。"
    )
    type: str = Field(
        ...,
        description="业务类型，如 String / Integer / Boolean / Float / List[string] / List[object] / Object。",
    )
    filterable: bool
    sortable: bool
    searchable: bool = Field(..., description="是否参与 query（BM25 全文搜索）。")
    default_returned: bool = Field(..., description="未指定 fields 时是否默认返回。")
    description: str | None = Field(None, description="人类可读的字段说明（中文）。")
    sample_values: list[str] | None = Field(
        None,
        description="该字段的取值样本（仅 enum-like 字段；高 cardinality 字段为空）。",
    )
    operators: list[str] | None = Field(
        None, description="适用的 FilterOperator 名（参考性，后端不强校验）。"
    )


class ApiError(BaseModel):
    code: str
    message: str
    request_id: str | None = None


class SearchPapersResponse(BaseModel):
    results: list[PaperMetadata] = Field(
        ..., description="命中论文列表（后端字段名为 results，非 hits）。"
    )
    total_count: int = Field(
        ...,
        description="命中总数；超过 10000 会被截断为 10000，需精确值时改用深翻页/计数。",
    )
    page: int
    page_size: int
    total_pages: int | None = Field(None, description="总页数。")
    next_cursor: str | None = Field(
        None,
        description="深翻页游标，为空表示无更多。page*page_size>10000 时必须改用 cursor（把此值回填到请求的 cursor）。",
    )
    search_time_ms: float | None = Field(None, description="检索耗时（毫秒）。")
    request_tokens: int | None = Field(None, description="输入 query 的 token 数。")
    response_tokens: int | None = Field(
        None, description="输出结果文本字段的 token 数。"
    )


class SemanticSearchResponse(BaseModel):
    hits: list[SearchChunk]


class CatalogResponse(BaseModel):
    fields: list[FieldCatalogEntry]
    default_fields: list[str] = Field(
        ..., description="search_papers 不传 fields 时默认返回的字段名清单。"
    )
    filter_operators: list[str] = Field(
        ...,
        description='支持的 FilterOperator 名（不带 FILTER_OP_ 前缀，如 "EQ" / "IN" / "CONTAINS"）。',
    )
