# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class Operator(Enum):
    FILTER_OP_EQ = "FILTER_OP_EQ"
    FILTER_OP_NE = "FILTER_OP_NE"
    FILTER_OP_GT = "FILTER_OP_GT"
    FILTER_OP_GTE = "FILTER_OP_GTE"
    FILTER_OP_LT = "FILTER_OP_LT"
    FILTER_OP_LTE = "FILTER_OP_LTE"
    FILTER_OP_IN = "FILTER_OP_IN"
    FILTER_OP_NIN = "FILTER_OP_NIN"
    FILTER_OP_CONTAINS = "FILTER_OP_CONTAINS"


class FiltersAdvancedItem(BaseModel):
    field: str
    operator: Operator | None = "FILTER_OP_EQ"
    value: Any


class SortByYear(Enum):
    desc = "desc"
    asc = "asc"
    none = "none"


class SearchPapersRequest(BaseModel):
    query: str | None = Field(
        None,
        description="BM25 全文关键词，匹配标题/摘要/期刊名/关键词字段。留空则纯靠结构化过滤。",
    )
    title_contains: str | None = Field(
        None, description="标题中必须包含的词（仅匹配 title 字段）。"
    )
    abstract_contains: str | None = Field(
        None, description="摘要中必须包含的词（仅匹配 abstract 字段）。"
    )
    authors: list[str] | None = Field(
        None,
        description="作者名（任一命中即可）。SDK 内部映射到后端 `author` 字段（FILTER_OP_IN）。",
    )
    year_from: int | None = Field(None, description="起始发表年（含）。")
    year_to: int | None = Field(None, description="结束发表年（含）。")
    journals: list[str] | None = Field(
        None,
        description="期刊名（任一命中即可）。SDK 内部映射到后端 `publication_venue_name` 字段（FILTER_OP_IN）。",
    )
    subjects: list[str] | None = Field(
        None, description='学科分类，如 "computer science"、"biology"。'
    )
    filters_advanced: list[FiltersAdvancedItem] | None = Field(
        None, description="高级过滤逃生舱（仅当上述字段不够用时使用）。"
    )
    sort_by_year: SortByYear | None = "desc"
    page: int | None = Field(1, ge=1)
    page_size: int | None = Field(10, ge=1, le=50)


class PaperMetadata(BaseModel):
    """
    文献元数据。字段名与 metadata-service 后端 `fields.py` 的真实字段一致，
    SDK 不做响应转换。`doc_id` 由 metadata-service 注入（OpenSearch `_id`）。

    """

    doc_id: str = Field(
        ..., description="文献唯一 ID（OpenSearch _id，通常为内容 sha256）。"
    )
    title: str
    author: list[str] | None = Field(
        None,
        description="作者列表（fields.py 中字段名是 author 单数，但类型是 List[string]）。",
    )
    abstract: str | None = None
    publication_venue_name: str | None = Field(
        None, description="期刊/会议名（fields.py 中是 String 类型）。"
    )
    publication_published_year: int | None = None
    subjects: list[str] | None = None
    keywords: list[str] | None = None
    doi: str | None = None


class SourceType(Enum):
    web = "web"
    pdf = "pdf"


class Mode(Enum):
    """
    fast = 仅关键词召回 (~200ms)；balanced = 混合检索 (~600ms)；quality = LLM 改写 + 混合 (~2-4s)。

    """

    fast = "fast"
    balanced = "balanced"
    quality = "quality"


class SemanticSearchRequest(BaseModel):
    query: str = Field(
        ..., description="自然语言查询，1-200 字最佳。", max_length=4096, min_length=1
    )
    top_k: int | None = Field(10, ge=1, le=30)
    source_types: list[SourceType] | None = None
    mode: Mode | None = Field(
        "balanced",
        description="fast = 仅关键词召回 (~200ms)；balanced = 混合检索 (~600ms)；quality = LLM 改写 + 混合 (~2-4s)。\n",
    )


class SearchChunk(BaseModel):
    chunk_id: str
    doc_id: str
    title: str
    abstract: str | None = None
    chunk: str | None = None
    score: float
    offset: int = Field(
        ..., description="chunk 在原文中的字节偏移，可直接传给 read_content。"
    )
    page_no: int | None = None
    source_type: str | None = None


class ReadContentResponse(BaseModel):
    text: str
    bytes_returned: int
    next_offset: int
    more: bool = Field(
        ..., description="为 true 表示可能还有后续字节，可用 next_offset 继续请求。"
    )


class FieldCatalogEntry(BaseModel):
    name: str = Field(
        ..., description="字段名（与 search_papers 的 filters[].field 一致）。"
    )
    type: str = Field(
        ...,
        description="业务类型，如 String / Integer / Boolean / Float / List[string] / List[object] / Object。",
    )
    filterable: bool
    sortable: bool
    searchable: bool = Field(..., description="是否参与 query（BM25 全文搜索）。")
    default_returned: bool = Field(..., description="未指定 fields 时是否默认返回。")
    description: str | None = Field(None, description="人类可读的字段说明（中文）。")
    sample_values: list[str] | None = Field(
        None,
        description="该字段的取值样本（仅 enum-like 字段；高 cardinality 字段为空）。",
    )
    operators: list[str] | None = Field(
        None, description="适用的 FilterOperator 名（参考性，后端不强校验）。"
    )


class ApiError(BaseModel):
    code: str
    message: str
    request_id: str | None = None


class SearchPapersResponse(BaseModel):
    hits: list[PaperMetadata]
    total: int
    page: int
    page_size: int


class SemanticSearchResponse(BaseModel):
    hits: list[SearchChunk]


class CatalogResponse(BaseModel):
    fields: list[FieldCatalogEntry]
    default_fields: list[str] = Field(
        ..., description="search_papers 不传 fields 时默认返回的字段名清单。"
    )
    filter_operators: list[str] = Field(
        ...,
        description='支持的 FilterOperator 名（不带 FILTER_OP_ 前缀，如 "EQ" / "IN" / "CONTAINS"）。',
    )
