# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-04-30T06:15:39+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class Operator(Enum):
    FILTER_OP_EQ = "FILTER_OP_EQ"
    FILTER_OP_NE = "FILTER_OP_NE"
    FILTER_OP_GT = "FILTER_OP_GT"
    FILTER_OP_GTE = "FILTER_OP_GTE"
    FILTER_OP_LT = "FILTER_OP_LT"
    FILTER_OP_LTE = "FILTER_OP_LTE"
    FILTER_OP_IN = "FILTER_OP_IN"
    FILTER_OP_NIN = "FILTER_OP_NIN"
    FILTER_OP_CONTAINS = "FILTER_OP_CONTAINS"


class FiltersAdvancedItem(BaseModel):
    field: str
    operator: Operator | None = "FILTER_OP_EQ"
    value: Any


class SortByYear(Enum):
    desc = "desc"
    asc = "asc"
    none = "none"


class SearchPapersRequest(BaseModel):
    query: str | None = Field(
        None, description="BM25 关键词，匹配标题/摘要/作者。留空则纯靠 filters 过滤。"
    )
    title_contains: str | None = Field(
        None, description="标题中必须包含的词（仅匹配 title 字段）。"
    )
    abstract_contains: str | None = Field(
        None, description="摘要中必须包含的词（仅匹配 abstract 字段）。"
    )
    authors: list[str] | None = Field(None, description="作者名匹配（任一命中）。")
    year_from: int | None = Field(None, description="起始发表年（含）。")
    year_to: int | None = Field(None, description="结束发表年（含）。")
    journals: list[str] | None = None
    subjects: list[str] | None = Field(
        None, description='学科分类，如 "computer science"、"biology"。'
    )
    filters_advanced: list[FiltersAdvancedItem] | None = Field(
        None, description="高级过滤逃生舱（仅当上述字段不够用时使用）。"
    )
    sort_by_year: SortByYear | None = "desc"
    page: int | None = Field(1, ge=1)
    page_size: int | None = Field(10, ge=1, le=50)


class PaperMetadata(BaseModel):
    doc_id: str
    title: str
    authors: list[str] | None = None
    abstract: str | None = None
    journal: str | None = None
    publication_published_year: int | None = None
    subjects: list[str] | None = None


class SourceType(Enum):
    web = "web"
    pdf = "pdf"


class Mode(Enum):
    """
    fast = 仅关键词召回 (~200ms)；balanced = 混合检索 (~600ms)；quality = LLM 改写 + 混合 (~2-4s)。

    """

    fast = "fast"
    balanced = "balanced"
    quality = "quality"


class SemanticSearchRequest(BaseModel):
    query: str = Field(
        ..., description="自然语言查询，1-200 字最佳。", max_length=4096, min_length=1
    )
    top_k: int | None = Field(10, ge=1, le=30)
    source_types: list[SourceType] | None = None
    mode: Mode | None = Field(
        "balanced",
        description="fast = 仅关键词召回 (~200ms)；balanced = 混合检索 (~600ms)；quality = LLM 改写 + 混合 (~2-4s)。\n",
    )


class SearchChunk(BaseModel):
    chunk_id: str
    doc_id: str
    title: str
    abstract: str | None = None
    chunk: str | None = None
    score: float
    offset: int = Field(
        ..., description="chunk 在原文中的字节偏移，可直接传给 read_content。"
    )
    page_no: int | None = None
    source_type: str | None = None


class ReadContentResponse(BaseModel):
    text: str
    bytes_returned: int
    next_offset: int
    more: bool = Field(
        ..., description="为 true 表示可能还有后续字节，可用 next_offset 继续请求。"
    )


class ApiError(BaseModel):
    code: str
    message: str
    request_id: str | None = None


class SearchPapersResponse(BaseModel):
    hits: list[PaperMetadata]
    total: int
    page: int
    page_size: int


class SemanticSearchResponse(BaseModel):
    hits: list[SearchChunk]
