#!/usr/bin/env node
// 派生 src/generated/tools.ts：从 ../../openapi.yaml 抽出三个 operation 的 name + description + input schema。
// 构建期跑一次（npm run gen），运行时零 yaml 依赖。
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import YAML from "yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const OPENAPI = resolve(ROOT, "../../openapi.yaml");
const OUT = resolve(ROOT, "src/generated/tools.ts");

const spec = YAML.parse(readFileSync(OPENAPI, "utf8"));

function inlineRefs(node) {
  if (Array.isArray(node)) return node.map(inlineRefs);
  if (node && typeof node === "object") {
    if (typeof node.$ref === "string" && Object.keys(node).length === 1) {
      if (!node.$ref.startsWith("#/")) throw new Error(`only local $ref supported: ${node.$ref}`);
      let target = spec;
      for (const part of node.$ref.slice(2).split("/")) target = target[part];
      return inlineRefs(JSON.parse(JSON.stringify(target)));
    }
    const out = {};
    for (const [k, v] of Object.entries(node)) out[k] = inlineRefs(v);
    return out;
  }
  return node;
}

function getRequestSchema(op) {
  if (op.requestBody) {
    return inlineRefs(op.requestBody.content["application/json"].schema);
  }
  const properties = {};
  const required = [];
  for (const param of op.parameters ?? []) {
    if (param.in !== "query") continue;
    const prop = inlineRefs(param.schema);
    if (param.description) prop.description = param.description;
    properties[param.name] = prop;
    if (param.required) required.push(param.name);
  }
  return { type: "object", properties, required };
}

function enDescription(op) {
  return (op["x-en-description"] || op["x-en-summary"] || op.description || op.summary || "").trim();
}

const tools = [];
const endpoints = {};
for (const [path, methods] of Object.entries(spec.paths)) {
  for (const [method, op] of Object.entries(methods)) {
    if (method !== "get" && method !== "post") continue;
    const id = op.operationId;
    tools.push({
      name: id,
      description: enDescription(op),
      inputSchema: getRequestSchema(op),
    });
    endpoints[id] = { method: method.toUpperCase(), path };
  }
}

const version = spec.info["x-sciverse-tools-version"] ?? spec.info.version;

mkdirSync(dirname(OUT), { recursive: true });
const body = `// Auto-generated by scripts/gen-tools.mjs. Do not edit.
// Source of truth: agent-tools/openapi.yaml

export const TOOLS_VERSION = ${JSON.stringify(version)};

export interface ToolDef {
  name: string;
  description: string;
  inputSchema: Record<string, unknown>;
}

export const TOOLS: ToolDef[] = ${JSON.stringify(tools, null, 2)};

export const ENDPOINTS: Record<string, { method: "GET" | "POST"; path: string }> = ${JSON.stringify(endpoints, null, 2)};
`;
writeFileSync(OUT, body, "utf8");
console.log(`wrote ${OUT} (${tools.length} tools, version ${version})`);
